repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0470f7c8a653e950f7cc5a653204ceb3fde4c02a # v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # NOTE: Ruff does not check for python code in some part of the documentation,
  # e.g. python code block, ..., see https://github.com/astral-sh/ruff/issues/8237
  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==25.1.0]
        args: ["--line-length=120"]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 69b77b8d2436cb00c886f129dda7f68f3b2909ac # v2.11.0
    hooks:
      - id: pyproject-fmt
        files: ^packages/bdm-python-shared-volume/pyproject\.toml$
        args: [--keep-full-version]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: 81b795a41ddcc3c77218d8c8e406983e39852285 # v1.1.408
    hooks:
      - id: pyright
        files: ^packages/bdm-python-shared-volume/
        args: [--project, packages/bdm-python-shared-volume, --venvpath, packages/bdm-python-shared-volume]
        exclude: ^packages/bdm-python-shared-volume/doc/source/conf.py$

  - repo: https://github.com/python-poetry/poetry
    rev: a84cd0f1bedb5769ef6ef7389d8ee99b93b9ba4c # frozen: v2.3.2
    hooks:
      - id: poetry-check
        entry: poetry -C packages/bdm-python-shared-volume check

  - repo: https://github.com/PyCQA/bandit
    rev: 92ae8b82fb422a639f0ed8d99e96cea769594e08 # v1.9.4
    hooks:
      - id: bandit
        args: ["-c", "packages/bdm-python-shared-volume/pyproject.toml", "--severity-level",
          "high", "-r", "."]
        additional_dependencies: ["bandit[toml]"]
 