repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: 2ca41cc1372d1e939a6a879f18cdc19fc1cac1ce # frozen: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # 1.29.0
    hooks:
      - id: zizmor
        args: ["--pedantic"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        exclude: ^doc/styles/Vocab/ANSYS/accept\.txt$
        args: [--ignore-words=doc/styles/Vocab/ANSYS/accept.txt]

  - repo: https://github.com/google/yamlfmt
    rev: b5ca1890231d5e1e5181fef75a1be609d1e25029 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
        exclude: '^packages/saf-cli/src/ansys/saf/cli/_solutions/templates/solution/\{\{cookiecutter\.'
        args:
          - "-formatter"
          - "max_line_length=80,retain_line_breaks=true,retain_line_breaks_single=true"

  - repo: https://github.com/ansys/pre-commit-hooks
    rev: ad4e7598809ad98cde5aaf52d80040c7ac56e7cf # v0.7.2
    hooks:
      - id: add-license-headers
        files: '\.(py|bat|html|css|proto)$'
        exclude: 'src/ansys/saf/desktop/installer/_package/assets/bootstrap\.min\.css'
        args:
          - --custom_license=Apache-2.0
          - --start_year=2026

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0470f7c8a653e950f7cc5a653204ceb3fde4c02a # v0.15.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 69b77b8d2436cb00c886f129dda7f68f3b2909ac # v2.11.0
    hooks:
      - id: pyproject-fmt
        files: ^(pyproject\.toml|packages/[^/]+/pyproject\.toml)$
        args: [--keep-full-version]

  # NOTE: Ruff does not check for python code in some part of the documentation,
  # e.g. python code block, ..., see https://github.com/astral-sh/ruff/issues/8237
  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==25.1.0]
        args: ["--line-length=120"]
