# Copyright (C) 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Unit tests for the ProjectsDashboard Dash component.

These tests verify the Python component class generated by dash-generate-components.
Run with: pytest tests/unit/test_projects_dashboard_component.py -v
"""

import pytest


class TestProjectsDashboardComponent:
    """Tests for the ProjectsDashboard Dash component."""

    @pytest.fixture
    def dashboard_component(self):
        """Import and return the ProjectsDashboard component class."""
        # Import inside fixture to allow tests to run even if component not built yet
        try:
            from ansys_saf_projects_dashboard import ProjectsDashboard

            return ProjectsDashboard
        except ImportError:
            pytest.skip("ProjectsDashboard component not built yet. Run 'npm run build' first.")

    def test_component_import(self, dashboard_component):
        """Test that the component can be imported."""
        assert dashboard_component is not None
        assert dashboard_component.__name__ == "ProjectsDashboard"

    def test_component_instantiation(self, dashboard_component):
        """Test that the component can be instantiated with default props."""
        component = dashboard_component(id="test-dashboard")
        assert component.id == "test-dashboard"

    def test_component_with_projects(self, dashboard_component):
        """Test that the component accepts projects prop."""
        projects = [
            {"name": "projects/1", "display_name": "Project 1"},
            {"name": "projects/2", "display_name": "Project 2"},
        ]
        component = dashboard_component(id="test", projects=projects)
        assert component.projects == projects

    def test_component_with_loading_state(self, dashboard_component):
        """Test that the component accepts loading prop."""
        component = dashboard_component(id="test", loading=True)
        assert component.loading is True

        component_false = dashboard_component(id="test2", loading=False)
        assert component_false.loading is False

    def test_component_with_error(self, dashboard_component):
        """Test that the component accepts error prop."""
        component = dashboard_component(id="test", error="Test error message")
        assert component.error == "Test error message"

    def test_component_with_notification(self, dashboard_component):
        """Test that the component accepts notification prop."""
        notification = {"message": "Success!", "type": "success"}
        component = dashboard_component(id="test", notification=notification)
        assert component.notification == notification

    def test_component_with_action_result(self, dashboard_component):
        """Test that the component accepts actionResult prop."""
        action_result = {
            "action": "create",
            "success": True,
            "projectId": "projects/123",
            "message": "Project created",
            "timestamp": 1706000000000,
        }
        component = dashboard_component(id="test", actionResult=action_result)
        assert component.actionResult == action_result

    def test_component_with_selected_project(self, dashboard_component):
        """Test that the component accepts selectedProject prop."""
        project = {"name": "projects/1", "display_name": "Selected Project"}
        component = dashboard_component(id="test", selectedProject=project)
        assert component.selectedProject == project

    def test_component_with_show_create_form(self, dashboard_component):
        """Test that the component accepts showCreateForm prop."""
        component = dashboard_component(id="test", showCreateForm=True)
        assert component.showCreateForm is True

    def test_component_with_pending_delete_id(self, dashboard_component):
        """Test that the component accepts pendingDeleteId prop."""
        component = dashboard_component(id="test", pendingDeleteId="projects/123")
        assert component.pendingDeleteId == "projects/123"

    def test_component_namespace(self, dashboard_component):
        """Test that the component has correct namespace."""
        component = dashboard_component(id="test")
        assert component._namespace == "ansys_saf_projects_dashboard"

    def test_component_type(self, dashboard_component):
        """Test that the component has correct type."""
        component = dashboard_component(id="test")
        assert component._type == "ProjectsDashboard"


class TestProjectsDashboardIntegration:
    """Integration tests for ProjectsDashboard with Dash callbacks."""

    @pytest.fixture
    def dash_app(self):
        """Create a Dash app for testing."""
        try:
            from dash import Dash, html

            from ansys_saf_projects_dashboard import ProjectsDashboard

            app = Dash(__name__)
            app.layout = html.Div(
                [
                    ProjectsDashboard(id="dashboard"),
                    html.Div(id="output"),
                ],
            )

            return app, ProjectsDashboard
        except ImportError:
            pytest.skip("Dash or ProjectsDashboard not available")

    def test_callback_on_action_result(self, dash_app):
        """Test that actionResult can be used in callbacks."""
        app, ProjectsDashboard = dash_app  # noqa: N806

        # Verify the component has actionResult as a valid property
        component = ProjectsDashboard(id="test")
        assert "actionResult" in component.available_properties

    def test_callback_on_projects_change(self, dash_app):
        """Test that projects can be used in callbacks."""
        app, ProjectsDashboard = dash_app  # noqa: N806

        component = ProjectsDashboard(id="test")
        assert "projects" in component.available_properties

    def test_all_expected_properties(self, dash_app):
        """Test that all expected properties are available."""
        app, ProjectsDashboard = dash_app  # noqa: N806

        component = ProjectsDashboard(id="test")
        expected_props = [
            "id",
            "projects",
            "loading",
            "error",
            "selectedProject",
            "showCreateForm",
            "notification",
            "actionResult",
            "pendingDeleteId",
        ]

        for prop in expected_props:
            assert prop in component.available_properties, f"Missing property: {prop}"


class TestProjectDataStructure:
    """Tests for Project data structure validation."""

    def test_valid_project_structure(self):
        """Test valid project data structure."""
        project = {
            "name": "projects/abc123",
            "display_name": "My Project",
            "date_created": "2025-01-01T10:00:00Z",
            "date_modified": "2025-01-15T14:30:00Z",
        }

        assert "name" in project
        assert "display_name" in project
        assert project["name"].startswith("projects/")

    def test_minimal_project_structure(self):
        """Test minimal valid project structure."""
        project = {
            "name": "projects/min",
            "display_name": "Minimal",
        }

        # Only name and display_name are required
        assert "name" in project
        assert "display_name" in project


class TestActionResultStructure:
    """Tests for ActionResult data structure."""

    @pytest.mark.parametrize("action", ["create", "update", "delete", "import", "export", "upgrade", "list"])
    def test_valid_action_types(self, action):
        """Test all valid action types."""
        action_result = {
            "action": action,
            "success": True,
            "timestamp": 1706000000000,
        }

        assert action_result["action"] == action
        assert action_result["success"] is True

    def test_action_result_with_project_id(self):
        """Test action result with project ID."""
        action_result = {
            "action": "create",
            "success": True,
            "projectId": "projects/new-123",
            "message": "Project created successfully",
            "timestamp": 1706000000000,
        }

        assert action_result["projectId"] == "projects/new-123"
        assert action_result["message"] == "Project created successfully"

    def test_action_result_failure(self):
        """Test action result for failed operation."""
        action_result = {
            "action": "delete",
            "success": False,
            "projectId": "projects/123",
            "message": "Permission denied",
            "timestamp": 1706000000000,
        }

        assert action_result["success"] is False
        assert "Permission denied" in action_result["message"]


class TestNotificationStructure:
    """Tests for Notification data structure."""

    @pytest.mark.parametrize("notification_type", ["success", "error", "info", "warning"])
    def test_valid_notification_types(self, notification_type):
        """Test all valid notification types."""
        notification = {
            "message": "Test message",
            "type": notification_type,
        }

        assert notification["type"] == notification_type

    def test_notification_message(self):
        """Test notification with message."""
        notification = {
            "message": "Project created successfully!",
            "type": "success",
        }

        assert notification["message"] == "Project created successfully!"
