name: Doc

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ""
    secrets:
      PYANSYS_CI_BOT_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-doc
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }} # No cancellation for main branch, to ensure that the workflow runs to completion and deploys the documentation if needed.

permissions: {}

env:
  CNAME: ${{ vars.CNAME }}
  DISABLE_INTERSPHINX: true

jobs:
  doc-get-changes:
    name: "Documentation changes detection"
    permissions:
      contents: read
      pull-requests: read # Required to read the pull-request to check if it has documentation changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Checkout repository
        if: github.event_name != 'workflow_dispatch' && !contains(github.workflow,
          'Certify')
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Detect docs related changes
        if: github.event_name != 'workflow_dispatch' && !contains(github.workflow,
          'Certify')
        id: detect
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        with:
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha
            || github.event.before }}
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
            || github.sha }}
          filters: .github/changes_doc_filters.yaml

  doc-centralized-build:
    name: "Centralized documentation building"
    if: (github.event_name != 'pull_request' && github.event_name != 'push') || contains(fromJSON(needs.doc-get-changes.outputs.changes),
      'documentation') # It should also run when called from certification
    needs: doc-get-changes
    timeout-minutes: 15
    permissions:
      contents: read # Allows this job to read the repository content for documentation build.
    runs-on: ubuntu-latest
    steps:
      - name: Check documentation style
        if: github.event_name == 'pull_request'
        uses: ansys/actions/doc-style@7410037bfb276c79ae91eb3617b9f5d2876f0c94 # v11.0.8
        with:
          token: ${{ github.token }}
          vale-version: '2.30.0'

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ startsWith(github.ref_name, 'release') && 'main' || github.ref
            }}
          fetch-depth: 0

      - name: Setup Moon Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4

      - name: Build centralized documentation
        shell: bash
        run: moon run doc:build-doc

      - name: Upload HTML documentation artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ vars.DOC_ARTIFACT }}-html
          path: doc/_build/html
          retention-days: 7

  doc-api-build-moon:
    name: "API documentation building (Moon)"
    needs: doc-get-changes
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        package:
          - bdm-python-api
          - saf-iam-oidc
    env:
      PACKAGE: ${{ matrix.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ (inputs.ref != '' && contains(inputs.ref, matrix.package)) && inputs.ref
            || (inputs.ref != '' && 'main' || github.ref) }}
          fetch-depth: 0

      - name: Setup Moon Toolchain
        uses: moonrepo/setup-toolchain@261c62cb5b0f580c7be7c8cd0f023a2e96756095 # v0.6.4

      - name: Build centralized documentation
        shell: bash
        run: moon run $PACKAGE:build-api-doc

      - name: Upload HTML documentation artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ vars.DOC_ARTIFACT }}-${{ matrix.package }}-html
          path: packages/${{ matrix.package }}/doc/_build/html
          overwrite: true
          if-no-files-found: error

      - name: Get version
        id: info
        uses: ansys/saf-devops/get-information-from-pyproject@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          pyproject-path: packages/${{ matrix.package }}/pyproject.toml

      - name: Deploy dev doc
        if: ${{ contains(steps.info.outputs.patch-version, 'dev') }}
        uses: ansys/actions/doc-deploy-dev@7410037bfb276c79ae91eb3617b9f5d2876f0c94 # v11.0.8
        with:
          cname: ${{ vars.CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          doc-artifact-name: ${{ vars.DOC_ARTIFACT }}-${{ matrix.package }}-html
          bot-user: "github-actions"
          bot-email: "github-actions@github.com"
          repository: ${{ github.repository }}
          branch: gh-pages-${{ matrix.package }}

      - name: Deploy stable doc
        if: ${{ !contains(steps.info.outputs.patch-version, 'dev') }}
        uses: ansys/saf-devops/doc-deploy-stable@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          cname: ${{ vars.CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          render-last: "5"
          doc-artifact-name: ${{ vars.DOC_ARTIFACT }}-${{ matrix.package }}-html
          bot-user: "github-actions"
          bot-email: "github-actions@github.com"
          version: ${{ steps.info.outputs.major-version }}.${{ steps.info.outputs.minor-version
            }}
          repository: ${{ github.repository }}
          branch: gh-pages-${{ matrix.package }}

  doc-api-build:
    name: "API documentation building"
    needs: doc-get-changes
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        package:
          - dash-super-components
          - glow-engine
          - saf-product-configuration
          - saf-product-manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ (inputs.ref != '' && contains(inputs.ref, matrix.package)) && inputs.ref
            || (inputs.ref != '' && 'main' || github.ref) }}
          fetch-depth: 0
          persist-credentials: false
          sparse-checkout: |
            packages/${{ matrix.package }}

      - name: Install dependencies
        id: prepare-env
        uses: ansys/saf-devops/prepare-python-environment@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          poetry-version: ${{ vars.POETRY_VERSION }}
          poetry-install-args: '--with doc --all-extras'
          python-project-path: packages/${{ matrix.package }}

      - name: Build ${{ matrix.package }} API documentation
        env:
          POETRY_EXE: ${{ steps.prepare-env.outputs.poetry-cmd }}
        working-directory: packages/${{ matrix.package }}
        run: ${POETRY_EXE} run make -C doc html SPHINXOPTS="-j auto -W --keep-going"

      - name: Upload API documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ vars.DOC_ARTIFACT }}-${{ matrix.package }}-html
          path: packages/${{ matrix.package }}/doc/_build/html
          overwrite: true
          if-no-files-found: error

      - name: Get version
        id: info
        uses: ansys/saf-devops/get-information-from-pyproject@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          pyproject-path: packages/${{ matrix.package }}/pyproject.toml

      - name: Deploy dev doc
        if: ${{ contains(steps.info.outputs.patch-version, 'dev') }}
        uses: ansys/actions/doc-deploy-dev@7410037bfb276c79ae91eb3617b9f5d2876f0c94 # v11.0.8
        with:
          cname: ${{ vars.CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          doc-artifact-name: ${{ vars.DOC_ARTIFACT }}-${{ matrix.package }}-html
          bot-user: "github-actions"
          bot-email: "github-actions@github.com"
          repository: ${{ github.repository }}
          branch: gh-pages-${{ matrix.package }}

      - name: Deploy stable doc
        if: ${{ !contains(steps.info.outputs.patch-version, 'dev') }}
        uses: ansys/saf-devops/doc-deploy-stable@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          cname: ${{ vars.CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          render-last: "5"
          doc-artifact-name: ${{ vars.DOC_ARTIFACT }}-${{ matrix.package }}-html
          bot-user: "github-actions"
          bot-email: "github-actions@github.com"
          version: ${{ steps.info.outputs.major-version }}.${{ steps.info.outputs.minor-version
            }}
          repository: ${{ github.repository }}
          branch: gh-pages-${{ matrix.package }}

  doc-merge:
    name: "Merge documentation"
    needs:
      - doc-centralized-build
      - doc-api-build-moon
      - doc-api-build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages-bdm-python-api
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: gh-pages-bdm-python-api
          path: html/api/bdm-python-api
          clean: false

      - name: Checkout dash-super-components
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: gh-pages-dash-super-components
          path: html/api/dash-super-components
          clean: false

      - name: Checkout glow-engine
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: gh-pages-glow-engine
          path: html/api/glow-engine
          clean: false

      - name: Checkout saf-iam-oidc
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: gh-pages-saf-iam-oidc
          path: html/api/saf-iam-oidc
          clean: false

      - name: Checkout saf-product-configuration
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: gh-pages-saf-product-configuration
          path: html/api/saf-product-configuration
          clean: false

      - name: Checkout saf-product-manager
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: gh-pages-saf-product-manager
          path: html/api/saf-product-manager
          clean: false

      - name: Download centralized documentation artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ vars.DOC_ARTIFACT }}-html
          path: html

      - name: Update versions.json
        working-directory: html/api
        shell: python
        run: |
          import json
          import os
          from pathlib import Path

          cname = os.environ["CNAME"]
          packages = [
            "bdm-python-api",
            "dash-super-components",
            "glow-engine",
            "saf-iam-oidc",
            "saf-product-configuration",
            "saf-product-manager"
          ]

          for package in packages:
            versions_path = Path(f"{package}/versions.json")
            versions = json.loads(versions_path.read_text(encoding="utf-8"))
            for entry in versions:
              entry['url'] = entry['url'].replace(cname, f"{cname}/version/stable/api/{package}")

            versions_path.write_text(
              json.dumps(versions, indent=2) + "\n",
              encoding="utf-8",
            )

      - name: Upload merged documentation
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ vars.DOC_ARTIFACT }}-merged-html
          path: html
          overwrite: true
          if-no-files-found: error

  doc-deploy:
    permissions:
      contents: write # Required to push to gh-pages branch
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.ref == 'refs/heads/main'
    needs: doc-merge
    name: Documentation deployment
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: info
        uses: ansys/saf-devops/get-information-from-pyproject@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          pyproject-path: packages/saf-sdk/pyproject.toml

      - name: Deploy stable doc
        uses: ansys/saf-devops/doc-deploy-stable@baa22e0dcc7e6598c662b4c003b2aac5b860f466 # v1.0.0
        with:
          cname: ${{ vars.CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          render-last: "5"
          doc-artifact-name: ${{ vars.DOC_ARTIFACT }}-merged-html
          bot-user: "github-actions"
          bot-email: "github-actions@github.com"
          version: ${{ steps.info.outputs.major-version }}.${{ steps.info.outputs.minor-version
            }}
          repository: ${{ github.repository }}
          skip-dev-version: true
