# Workflow documented in architecture\ci-meta-package-execution.md
name: CI-CD for SAF SDK Meta Package
run-name: >-
  Meta-Package: ${{ inputs.release && 'Release' || 'Dry Run' }} by ${{ github.actor
  }} Update type: ${{ inputs.meta-package-version-update-type }} ${{ inputs.ansys-bdm-api-version-override
  != '' && format('BDM API Override: {0}', inputs.ansys-bdm-api-version-override)
  || '' }} ${{ inputs.ansys-bdm-shared-volume-version-override != '' && format('BDM
  Shared Volume Override: {0}', inputs.ansys-bdm-shared-volume-version-override) ||
  '' }} ${{ inputs.ansys-saf-glow-engine-version-override != '' && format('SAF Glow
  Engine Override: {0}', inputs.ansys-saf-glow-engine-version-override) || '' }} ${{
  inputs.ansys-saf-desktop-installer-version-override != '' && format('SAF Desktop
  Installer Override: {0}', inputs.ansys-saf-desktop-installer-version-override) ||
  '' }} ${{ inputs.ansys-saf-desktop-orchestrator-version-override != '' && format('SAF
  Desktop Orchestrator Override: {0}', inputs.ansys-saf-desktop-orchestrator-version-override)
  || '' }} ${{ inputs.ansys-iam-oidc-version-override != '' && format('IAM OIDC Override:
  {0}', inputs.ansys-iam-oidc-version-override) || '' }} ${{ inputs.ansys-saf-product-configuration-version-override
  != '' && format('SAF Product Configuration Override: {0}', inputs.ansys-saf-product-configuration-version-override)
  || '' }} ${{ inputs.ansys-saf-product-manager-version-override != '' && format('SAF
  Product Manager Override: {0}', inputs.ansys-saf-product-manager-version-override)
  || '' }}
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release ansys-saf-sdk package"
        required: false
        type: boolean
        default: false
      meta-package-version-update-type:
        description: "Requested SDK meta-package version update type"
        required: false
        type: choice
        options:
          - auto
          - major
          - minor
          - patch
        default: "auto"
      ansys-bdm-api-version-override:
        description: "Override for the Ansys BDM API version. Only for release branch."
        required: false
        type: string
        default: ""
      ansys-bdm-shared-volume-version-override:
        description: "Override for the Ansys BDM Shared Volume version. Only for release
          branch."
        required: false
        type: string
        default: ""
      ansys-saf-glow-engine-version-override:
        description: "Override for the Ansys SAF Glow Engine version. Only for release
          branch."
        required: false
        type: string
        default: ""
      ansys-saf-desktop-installer-version-override:
        description: "Override for the Ansys SAF Desktop Installer version. Only for
          release branch."
        required: false
        type: string
        default: ""
      ansys-saf-desktop-orchestrator-version-override:
        description: "Override for the Ansys SAF Desktop Orchestrator version. Only
          for release branch."
        required: false
        type: string
        default: ""
      ansys-iam-oidc-version-override:
        description: "Override for the Ansys IAM OIDC version. Only for release branch."
        required: false
        type: string
        default: ""
      ansys-saf-product-configuration-version-override:
        description: "Override for the Ansys SAF Product Configuration version. Only
          for release branch."
        required: false
        type: string
        default: ""
      ansys-saf-product-manager-version-override:
        description: "Override for the Ansys SAF Product Manager version. Only for
          release branch."
        required: false
        type: string
        default: ""
  workflow_call:
    secrets:
      PYANSYS_CI_BOT_TOKEN:
        required: true
      PYANSYS_PYPI_PRIVATE_PAT:
        required: true
      PYANSYS_PYPI_PRIVATE_URL:
        required: true
      BUMP_VERSION_TOKEN:
        required: false
      PYANSYS_CI_BOT_EMAIL:
        required: false
      PYANSYS_CI_BOT_USERNAME:
        required: false

# Apply the principle of least privilege to state at job level the right
# permissions. More information about workflow permissions in the page
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-meta-package
  cancel-in-progress: true

env:
  LIBRARY_NAME: saf-sdk
  MINIMUM_PIP_VERSION: '26.0' # Minimal version to have the dependency resolution to be successful

jobs:
  run-tests-action:
    name: "Run sdk_meta_package_utilities test"
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read the source code of the project
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Test SDK meta-package utility
        shell: bash
        run: uv run ".github/actions/sdk-meta-package/tests/run_tests.py"

  build-meta-package:
    name: "Build Meta Package"
    runs-on: ubuntu-latest
    permissions:
      attestations: write # Write attestation for uploaded distribution artifacts
      contents: read # Read the source code of the project
      id-token: write # Write access to a temporary token for signing attestations
    env:
      GITHUB_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }} # To be set to github.token when the repositories are public
    outputs:
      update-type: ${{ steps.update-pyproject.outputs.update-type }}
      version: ${{ steps.update-pyproject.outputs.version }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/actions/sdk-meta-package
            packages/${{ env.LIBRARY_NAME }}

      - name: Update pyproject.toml
        id: update-pyproject
        uses: ./.github/actions/sdk-meta-package
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          is-for-pypi-release: ${{ inputs.release && 'true' || 'false' }}
          minimum-pip-version: ${{ env.MINIMUM_PIP_VERSION }}
          meta-package-version-update-type: ${{ github.event_name == 'workflow_dispatch'
            && inputs.meta-package-version-update-type || 'auto' }}
          ansys-bdm-api-version-override: ${{ github.event_name == 'workflow_dispatch'
            && inputs.ansys-bdm-api-version-override || '' }}
          ansys-bdm-shared-volume-version-override: ${{ github.event_name == 'workflow_dispatch'
            && inputs.ansys-bdm-shared-volume-version-override || '' }}
          ansys-saf-glow-engine-version-override: ${{ github.event_name == 'workflow_dispatch'
            && inputs.ansys-saf-glow-engine-version-override || '' }}
          ansys-saf-desktop-installer-version-override: ${{ github.event_name == 'workflow_dispatch'
            && inputs.ansys-saf-desktop-installer-version-override || '' }}
          ansys-saf-desktop-orchestrator-version-override: ${{ github.event_name ==
            'workflow_dispatch' && inputs.ansys-saf-desktop-orchestrator-version-override
            || '' }}
          ansys-iam-oidc-version-override: ${{ github.event_name == 'workflow_dispatch'
            && inputs.ansys-iam-oidc-version-override || '' }}
          ansys-saf-product-configuration-version-override: ${{ github.event_name
            == 'workflow_dispatch' && inputs.ansys-saf-product-configuration-version-override
            || '' }}
          ansys-saf-product-manager-version-override: ${{ github.event_name == 'workflow_dispatch'
            && inputs.ansys-saf-product-manager-version-override || '' }}

      - name: "Build wheel"
        uses: ansys/actions/build-library@7410037bfb276c79ae91eb3617b9f5d2876f0c94 # v11.0.8
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          checkout: false
          working-directory: ${{ github.workspace }}/packages/${{ env.LIBRARY_NAME
            }}
          use-uv: true
          python-version: ${{ vars.PYTHON_VERSION }}
          attest-provenance: true
          validate-build: true

  check-wheel-can-be-poetry-installed:
    name: "Check ansys-saf-sdk can be poetry installed"
    needs: build-meta-package
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        python-version:
          - 3.11
          - 3.12
          - 3.13
          - 3.14
        runner:
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: wheels

      - name: Setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        shell: bash
        run: pipx install poetry==${POETRY_VERSION}
        env:
          POETRY_VERSION: ${{ vars.POETRY_VERSION }}

      - name: Configure Poetry and create new poetry project
        shell: bash
        run: |
          poetry config virtualenvs.in-project true
          poetry new my_project
          sed -i 's/^requires-python = .*/requires-python = ">=3.11,<3.15"/' my_project/pyproject.toml

      - name: Add ansys-saf-sdk to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/wheels/*.whl)
          poetry add "ansys-saf-sdk[all] @ file://${WHEEL_FILE}"

      - name: Download additional wheels
        shell: bash
        run: |
          python -m pip download --ignore-requires-python --no-deps -d ./pim-light-server ansys-saf-pim-light-server
          python -m pip download --ignore-requires-python --no-deps -d ./translation-utilities ansys-translation-utilities
          python -m pip download --ignore-requires-python --no-deps -d ./saf-desktop-portal ansys-saf-desktop-portal
          python -m pip download --ignore-requires-python --no-deps -d ./saf-web-portal ansys-saf-web-portal
          python -m pip download --ignore-requires-python --no-deps -d ./minerva-client ansys-minerva-python-client
          python -m pip download --ignore-requires-python --no-deps -d ./datarepository ansys-datarepository-python-client
          python -m pip download --ignore-requires-python --no-deps -d ./saf-hermes ansys-saf-hermes
          python -m pip download --ignore-requires-python --no-deps -d ./aspire ansys-saf-aspire
        env:
          PIP_QUIET: 1
          PIP_INDEX_URL: https://pypi.org/simple
          PIP_EXTRA_INDEX_URL: https://PAT:${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}@${{
            secrets.PYANSYS_PYPI_PRIVATE_URL }}

      - name: Add ansys-saf-pim-light-server to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/pim-light-server/*.whl)
          poetry add "ansys-saf-pim-light-server[all] @ file://${WHEEL_FILE}"

      - name: Add translation-utilities to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/translation-utilities/*.whl)
          poetry add "ansys-translation-utilities[all] @ file://${WHEEL_FILE}"

      - name: Add saf-desktop-portal to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/saf-desktop-portal/*.whl)
          poetry add "ansys-saf-desktop-portal[all] @ file://${WHEEL_FILE}"

      - name: Add minerva-client to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/minerva-client/*.whl)
          poetry add "ansys-minerva-python-client[all] @ file://${WHEEL_FILE}"

      - name: Add datarepository to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/datarepository/*.whl)
          poetry add "ansys-datarepository-python-client[all] @ file://${WHEEL_FILE}"

      - name: Add saf-hermes to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/saf-hermes/*.whl)
          poetry add "ansys-saf-hermes[all] @ file://${WHEEL_FILE}"

      - name: Add saf-web-portal to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/saf-web-portal/*.whl)
          poetry add "ansys-saf-web-portal[all] @ file://${WHEEL_FILE}"

      - name: Add aspire to poetry project
        working-directory: my_project
        shell: bash
        run: |
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/aspire/*.whl)
          poetry add "ansys-saf-aspire[all] @ file://${WHEEL_FILE}"

  check-wheel-can-be-pip-installed:
    name: Check wheel can be pip installed
    needs: build-meta-package
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        python-version:
          - 3.11
          - 3.12
          - 3.13
          - 3.14
        runner:
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: wheels

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip install ansys-saf-sdk wheel
        shell: bash
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: |
          ${PYTHON_PATH} -m venv .venv
          if [ $RUNNER_OS == "Windows" ]; then
            . .venv/Scripts/activate
          else
            . .venv/bin/activate
          fi

          python -m pip show pip
          python -m pip install --upgrade pip==${MINIMUM_PIP_VERSION}
          WHEEL_FILE=$(ls "${GITHUB_WORKSPACE}"/wheels/*.whl)
          python -m pip install "${WHEEL_FILE}"

  release-to-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-meta-package
      - check-wheel-can-be-poetry-installed
      - check-wheel-can-be-pip-installed
    if: ${{ inputs.release }}
    environment: saf-release
    permissions:
      id-token: write # Required for OIDC authentication with PyPI
      contents: write # Required for OIDC authentication with PyPI
    env:
      RELEASE_BRANCH_NAME: 'release/v${{ needs.build-meta-package.outputs.version
        }}/saf-sdk'
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true # required for pushing to the release branch

      - name: Create release branch
        shell: bash
        run: |
          git switch --create ${RELEASE_BRANCH_NAME}

      - name: Download pyproject.toml artifact
        if: ${{ needs.build-meta-package.outputs.update-type != 'no_update' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: pyproject
          path: artifacts

      - name: Download uv lock file artifact
        if: ${{ needs.build-meta-package.outputs.update-type != 'no_update' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: uv-lock
          path: artifacts

      - name: Move pyproject.toml and uv.lock to packages/saf-sdk
        if: ${{ needs.build-meta-package.outputs.update-type != 'no_update' }}
        shell: bash
        run: |
          mv artifacts/pyproject.toml packages/saf-sdk/pyproject.toml
          mv artifacts/uv.lock packages/saf-sdk/uv.lock

      - name: Edit version in the root pyproject.toml
        shell: bash
        env:
          VERSION: ${{ needs.build-meta-package.outputs.version }}
        run: |
          sed -i "s/^version = .*/version = \"${VERSION}\"/" pyproject.toml

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "chore: create release branch"
          git push origin HEAD:${RELEASE_BRANCH_NAME}

      - name: Download release notes artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: release-notes
          path: release-notes

      - name: "Download the library artifacts"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: ${{ env.LIBRARY_NAME }}-artifacts

      - name: Create release
        id: create-release
        run: |
          gh release create ${RELEASE_NAME} \
            --title ${RELEASE_NAME} \
            --notes-file release-notes/release_notes.md \
            --latest \
            --target ${RELEASE_BRANCH_NAME} \
            --attach "${LIBRARY_NAME}-artifacts"/*.whl
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_NAME: v${{ needs.build-meta-package.outputs.version }}-${{ env.LIBRARY_NAME
            }}

      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          repository-url: https://upload.pypi.org/legacy/
          print-hash: true
          packages-dir: ${{ env.LIBRARY_NAME }}-artifacts
          skip-existing: false

  create-pr:
    name: Update main branch with latest SAF SDK
    runs-on: ubuntu-latest
    needs:
      - build-meta-package
      - release-to-pypi
    permissions:
      contents: write # Create and push the merge branch
      pull-requests: write # Create the pull request
    env:
      RELEASE_BRANCH_NAME: release/v${{ needs.build-meta-package.outputs.version }}/saf-sdk
      MERGE_BRANCH_NAME: chore/bump-v${{ needs.build-meta-package.outputs.version
        }}/saf-sdk
    if: ${{ github.ref_name == 'main' && needs.build-meta-package.outputs.update-type
      != 'no_update' }}
    steps:
      - name: Checkout release branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ env.RELEASE_BRANCH_NAME }}
          fetch-depth: 0
          persist-credentials: true # required for pushing the branch

      - name: Create and push merge branch
        shell: bash
        run: |
          git switch --create "${MERGE_BRANCH_NAME}"
          git push --set-upstream origin "${MERGE_BRANCH_NAME}"

      - name: Create pull request
        shell: bash
        id: pr-info
        run: |
          git config --global user.email "${EMAIL}"
          git config --global user.name "${USERNAME}"

          pr_url=$(gh pr create \
            --base main \
            --head "${MERGE_BRANCH_NAME}" \
            --title "chore(bump): Bump saf-sdk to v${VERSION}" \
            --body "Bump the released SAF SDK version from ${RELEASE_BRANCH_NAME} into main."
          )
          echo "[pr-info] ℹ️ PR created: $pr_url"
          echo "pr-url=$pr_url" >> $GITHUB_OUTPUT

          # Extract PR number from URL
          pr_number=$(echo "$pr_url" | sed 's|.*/pull/||')
          echo "pr-number=$pr_number" >> $GITHUB_OUTPUT
        env:
          EMAIL: ${{ secrets.PYANSYS_CI_BOT_EMAIL != '' && secrets.PYANSYS_CI_BOT_EMAIL
            || 'actions@github.com' }}
          USERNAME: ${{ secrets.PYANSYS_CI_BOT_USERNAME != '' && secrets.PYANSYS_CI_BOT_USERNAME
            || 'actions' }}
          GH_TOKEN: ${{ secrets.BUMP_VERSION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BUMP_VERSION_TOKEN }}
          VERSION: ${{ needs.build-meta-package.outputs.version }}

      - name: Approve and Merge
        run: |
          gh pr edit "${PR_URL}" --add-label "auto-approve"
          gh pr review --approve "${PR_URL}"
          gh pr merge --auto --squash --delete-branch "${PR_URL}"
        env:
          GH_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN != '' && secrets.PYANSYS_CI_BOT_TOKEN
            || github.token }}
          PR_URL: ${{ steps.pr-info.outputs.pr-url }}
