// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['ansys_saf_projects_dashboard'];

pk.ImportExport.propTypes = {onImport:pt.any};
pk.Pagination.propTypes = {currentPage:pt.number,
 pageSize:pt.number,
 totalProjects:pt.number,
 totalPages:pt.number,
 onPageChange:pt.any,
 onPageSizeChange:pt.any};
pk.ProjectForm.propTypes = {project:pt.shape({name:pt.string,display_name:pt.string,description:pt.string,date_created:pt.string,date_modified:pt.string,icon:pt.string}),
 onSubmit:pt.any,
 onCancel:pt.any};
pk.ProjectInfo.propTypes = {project:pt.shape({name:pt.string,display_name:pt.string,description:pt.string,date_created:pt.string,date_modified:pt.string,icon:pt.string}),
 onClose:pt.any,
 onOpen:pt.any};
pk.ProjectsDashboard.propTypes = {apiBaseUrl:pt.string,
 projectIconUrl:pt.string,
 solutionImageUrl:pt.string,
 solutionDescription:pt.string,
 projects:pt.arrayOf(pt.shape({name:pt.string,display_name:pt.string,description:pt.string,date_created:pt.string,date_modified:pt.string,icon:pt.string})),
 loading:pt.bool,
 error:pt.string,
 selectedProject:pt.shape({name:pt.string,display_name:pt.string,description:pt.string,date_created:pt.string,date_modified:pt.string,icon:pt.string}),
 showCreateForm:pt.bool,
 notification:pt.shape({message:pt.string,type:pt.oneOf(['error','success','info','warning'])}),
 actionResult:pt.shape({action:pt.oneOf(['create','update','delete','import','export','upgrade','list']),projectId:pt.string,success:pt.bool,message:pt.string,timestamp:pt.number}),
 pendingDeleteId:pt.string,
 showUpgradeSnackbar:pt.bool,
 upgradeProjectId:pt.string,
 themeMode:pt.oneOf(['light','dark']),
 currentPage:pt.number,
 pageSize:pt.number,
 totalProjects:pt.number,
 totalPages:pt.number,
 filters:pt.shape({search:pt.string,dateCreatedFrom:pt.string,dateCreatedTo:pt.string,dateModifiedFrom:pt.string,dateModifiedTo:pt.string}),
 id:pt.string,
 setProps:pt.any};
pk.ProjectsFilter.propTypes = {value:pt.shape({search:pt.string,dateCreatedFrom:pt.string,dateCreatedTo:pt.string,dateModifiedFrom:pt.string,dateModifiedTo:pt.string}),
 onApply:pt.any,
 onClear:pt.any};
pk.ProjectsList.propTypes = {projects:pt.arrayOf(pt.shape({name:pt.string,display_name:pt.string,description:pt.string,date_created:pt.string,date_modified:pt.string,icon:pt.string})),
 projectIconUrl:pt.string,
 onEdit:pt.any,
 onDelete:pt.any,
 onExport:pt.any,
 onCardClick:pt.any,
 onFavoriteToggle:pt.any,
 onInfo:pt.any,
 favoriteIds:pt.arrayOf(pt.string)};
pk.ProjectsTable.propTypes = {projects:pt.arrayOf(pt.shape({name:pt.string,display_name:pt.string,description:pt.string,date_created:pt.string,date_modified:pt.string,icon:pt.string})),
 projectIconUrl:pt.string,
 onEdit:pt.any,
 onDelete:pt.any,
 onExport:pt.any,
 onCardClick:pt.any,
 onFavoriteToggle:pt.any,
 onInfo:pt.any,
 favoriteIds:pt.arrayOf(pt.string)};
pk.SolutionMetadata.propTypes = {solutionImageUrl:pt.string,
 solutionDescription:pt.string};
